---
- name: "Add Stable NGINX Repository"
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - deb https://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx
    - deb-src https://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx

- apt_key:
    url: https://nginx.org/keys/nginx_signing.key

- apt:
    update_cache: yes

- name: "Install NGINX"
  package:
    name: nginx
    state: present
  notify: "Start nginx"

- name: "Check for default site config"
  stat:
    path: /etc/nginx/conf.d/default.conf
  register: default_status

- name: "Remove default site config"
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  when: default_status.stat.exists == True

- name: "Template site config"
  template:
    src: ../templates/site.conf.j2
    dest: /etc/nginx/conf.d/{{ item.name }}.conf
    mode: 0644
    owner: nginx
  with_items: "{{sites}}"
  notify: "Reload nginx"
