---
- hosts: tag_ansible-managed:&tag_production:&tag_ssl-terminator:&tag_docker-host
  remote_user: root

  vars_files:
    - group_vars/production-provision.yml

  roles:
    - common
    - nginx
    - docker
    - transientbug-docker
