---
- hosts: tag_ansible-managed:&tag_staging:&tag_ssl-terminator:&tag_docker-host
  remote_user: root

  vars_files:
    - group_vars/staging.yml

  roles:
    - common
    - letsencrypt
    - nginx
    - docker
    - awscli
    - transientbug-docker
