---
- hosts: tag_ansible-managed:&tag_staging:&tag_ssl-terminator
  remote_user: root

  vars_files:
    - vars/users.yml
    - vars/ssl.yml
    - vars/nginx.yml

  roles:
    - common
    - letsencrypt
    - nginx
