---
- hosts: tag_ansible-managed:&tag_staging:&tag_ssl-terminator:&tag_docker-host
  remote_user: root

  vars_files:
    - vars/users.yml
    - vars/ssl.yml
    - vars/nginx.yml

  roles:
    #- common
    #- letsencrypt
    #- nginx
    #- docker
    - transientbug-docker
