---
- users:
  - name: ashby
    password: '$2y$10$G5hmiWAdGiOINyLAas4A5.Z7Fr3ttnKK0MVEQQO9MGpFNcQ71qNQy'
    shell: /bin/bash
    group: ashby
    groups:
      - users
      - sudo
      - wheel
    pubkeys_url: http://github.com/joshashby.keys
