---
- name: "Set the vm.max_map_count higher for ES"
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: "Check if we're a new install"
  stat: path=/opt/transientbug/
  register: repo_stats

- name: "Fetching transientBug repo"
  git:
    repo: https://github.com/transientBug/transientbug-rails.git
    dest: /opt/transientbug/

- name: "Ensuring storage is linked"
  file:
    src: "{{storage.mount}}"
    dest: "/opt/transientbug/storage/"
    state: link

- name: "Template the environment variables"
  template:
    src: ../templates/env.j2
    dest: /opt/transientbug/.env.production

- name: "Building new docker-compose stack"
  command: docker-compose -f docker-compose.deploy.yml build
  args:
    chdir: /opt/transientbug/

- name: "Setting up the database"
  command: docker-compose -f docker-compose.deploy.yml run rails bundle exec rake db:setup
  args:
    chdir: /opt/transientbug/
  when: repo_stats.stat.exists == False

- name: "Migrating the database"
  command: docker-compose -f docker-compose.deploy.yml run rails bundle exec rake db:migrate
  args:
    chdir: /opt/transientbug/
  when: repo_stats.stat.exists == True

#- name: "Building new docker-compose stack"
#  command: docker-compose -f docker-compose.deploy.yml run rails bundle exec rake assets:precompile
#  args:
#    chdir: /opt/transientbug/

- name: "Tearing down old stack"
  command: docker-compose -f docker-compose.deploy.yml down
  args:
    chdir: /opt/transientbug/

- name: "Bring new stack up"
  command: docker-compose -f docker-compose.deploy.yml up -d
  args:
    chdir: /opt/transientbug/
